### ISSUE TITLE
Is possible to use reply-to 

### ISSUE THREAD

**Issue by RenanSanguinete** [shihabmridha/react-native-smtp#3]
Someone knows if is possible to use reply-to?

I need to somehow specify other email to reply insted the email indicated on to field.

**Comment by shihabmridha** [comment]
Just published a new version to the [GitHub package](https://github.com/shihabmridha/react-native-smtp/packages/278711).

Example usage:
```
// Now send the mail
EmailSender.send(
  {
    from: 'from@email.com',
    to: 'to@email.com,another@email.com',
    subject: 'The subject',
    body: '<h3> Cool Body </h3>',
    replyTo: 'reply@email.com' // Optional
  },
  attachments, // This second parameter is mandatory. You can send an empty array.
);
```

**Comment by RenanSanguinete** [comment]
I did the update version, but I get now this errors:

Android 

When I try to build first I get this error:
/node_modules/react-native-smtp/android/src/main/java/com/reactnativesmtp/SmtpModule.java:142: error: unclosed character literal
So I change the '' to "" here:
 if (mailData.hasKey('replyTo')) 
and
message.setReplyTo(new InternetAddress(mailData.hasKey('replyTo')));

and now I get this error:

/node_modules/react-native-smtp/android/src/main/java/com/reactnativesmtp/SmtpModule.java:143: error: incompatible types: boolean cannot be converted to String
message.setReplyTo(new InternetAddress(mailData.hasKey("replyTo")));

iOS 
I'm using pods I get this error

TypeError: undefined is not a function (near '..._reactNativeSmtp.default.config...')

**Comment by shihabmridha** [comment]
The code had a syntax error.
Here is a new build: https://github.com/shihabmridha/react-native-smtp/packages/278711

**IMPORTANT: It doesn't support iOS (as mentioned in the Readme)**

**Comment by RenanSanguinete** [comment]
Sorry about the iOS, I see the manual installation set the commands for iOS and I didn't see the Android Only.

I install the 1.1.2 version directly, but I still get the error, but I could solved making some modifications on SmtpModule.java

String from, to, subject, body, **replyTo**;

// Set reply-to
if (mailData.hasKey("replyTo")) {
    replyTo = mailData.getString("replyTo");
    message.setReplyTo(InternetAddress.parse(replyTo));
}

Unfortunately i need to use on iOS too. I'll be using this one until I find other with this replyTo for iOS.
